/**
 * Creates frontend/.env.local (if absent) wired to the local Strapi CMS, so the
 * frontend reads live CMS content instead of the bundled mock data. Idempotent
 * — it never overwrites an existing file.
 */
import { writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const target = join(root, 'frontend', '.env.local');

if (existsSync(target)) {
  console.log('frontend/.env.local already exists — leaving it untouched.');
  process.exit(0);
}

const contents = `# Auto-generated by \`npm run setup\`. Edit as needed.
NEXT_PUBLIC_SITE_URL=http://localhost:3000
NEXT_PUBLIC_SITE_NAME=Meridian News

# Read live content from the local Strapi CMS (same Codespace/host).
NEXT_PUBLIC_STRAPI_URL=http://localhost:1337
NEXT_PUBLIC_STRAPI_API_URL=http://localhost:1337/api
NEXT_PUBLIC_STRAPI_GRAPHQL_URL=http://localhost:1337/graphql

# Use the CMS, not bundled mock data.
NEXT_PUBLIC_USE_MOCK_FALLBACK=false
`;

writeFileSync(target, contents);
console.log('Created frontend/.env.local pointing at http://localhost:1337');
