/**
 * Generates frontend/.env.local wired to the local Strapi CMS so the frontend
 * reads live content instead of bundled mock data.
 *
 * Auto-detects GitHub Codespaces and uses the forwarded HTTPS URL for media
 * (so uploaded images load in the browser) while keeping server-side API calls
 * on localhost for speed. Regenerates the file each run.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const target = join(root, 'frontend', '.env.local');

const cs = process.env.CODESPACE_NAME;
const domain = process.env.GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN;
const inCodespaces = Boolean(cs && domain);

// Server-side fetches stay on localhost (same host, fast, reliable).
const apiHost = 'http://localhost:1337';
// Browser-facing media host: public forwarded URL in Codespaces, else localhost.
const mediaHost = inCodespaces
  ? `https://${cs}-1337.${domain}`
  : 'http://localhost:1337';
const siteUrl = inCodespaces
  ? `https://${cs}-3000.${domain}`
  : 'http://localhost:3000';

const contents = `# Auto-generated by \`npm run setup\` / \`node scripts/write-env.mjs\`.
NEXT_PUBLIC_SITE_URL=${siteUrl}
NEXT_PUBLIC_SITE_NAME=Meridian News

# API calls (server-side) use localhost; media URLs (browser) use the media host.
NEXT_PUBLIC_STRAPI_URL=${mediaHost}
NEXT_PUBLIC_STRAPI_API_URL=${apiHost}/api
NEXT_PUBLIC_STRAPI_GRAPHQL_URL=${apiHost}/graphql

# Read live CMS content, not bundled mock data.
NEXT_PUBLIC_USE_MOCK_FALLBACK=false

# Load Strapi images directly in the browser (skip the optimizer) when the CMS
# is served over a forwarded/localhost port that the optimizer can't reach.
NEXT_PUBLIC_UNOPTIMIZED_IMAGES=${inCodespaces ? 'true' : 'false'}
`;

writeFileSync(target, contents);
console.log(
  `Wrote frontend/.env.local ${
    inCodespaces ? `(Codespaces: media at ${mediaHost})` : '(localhost)'
  }`,
);
